#!/usr/bin/env python
import math

#Find the area of a triangle with user input
# Sides a, b, & c are provided by user

def triangle_area(a,b,c):
    a = eval(input("Enter a number for side 'a': "))
    b = eval(input("Enter a number for  side 'b': "))
    c = eval(input("Enter a number for side 'c': "))
    s = (a + b + c) / 2
    A = math.sqrt(s * (s -a) * (s - b) * (s - c))
    print("The area of the triangle is ", A)

if __name__ == "__main__":
    print "print area"
    print "Note: triangle_area()"
    print(triangle_area(a, b,c))
